apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idp-system

resources:
  - control-plane/deployment.yaml
  - ml-engine/deployment.yaml
  - observability/

commonLabels:
  app.kubernetes.io/managed-by: idp-platform
  app.kubernetes.io/version: "0.1.0"